Repository MelvinCou/The-translation, pull requests merged in 2025-01, with the labels that each got.

#60 Slow down the servomotor speed
  include/Sorter.hpp
  src/Sorter.cpp
  src/production.cpp
Labels: production mode, servomotor

#66 fix: remove undefined behavior when parsing HTTP response bodies
  lib/Simulation/src/HTTPClient.cpp
  src/DolibarrClient.cpp
  src/production.cpp
Labels: bug

#72 Add document strategy file
  docs/Stratégie de tests.pdf
Labels: documentation
